Faction color in faction configuration popup title
Zetawar/zetawar pull request #77
Opened 2017-04-18 14:17 UTC by tbeddy

Closes #48
Alternatively, "with-let" could be changed to a simple "let" and the color information could instead be defined in its bindings.

2017-04-25 18:42 UTC, djwhitt requested changes

2017-04-25 18:42 UTC, djwhitt commented on src/cljs/zetawar/data.cljs
> -    :configure-faction-title "Configure faction"
I'd keep this and rename it to :configuration-faction-title-prefix. Also, I prefer "Configure faction" to "Configure Faction". I'm not a big fan of title case.

2017-04-25 18:42 UTC, djwhitt commented on src/cljs/zetawar/data.cljs
>      :configure-faction-tip"Configure faction"
Not your doing afaik, but we should add a space between the keyword and the string.

2017-04-25 18:42 UTC, djwhitt commented on src/cljs/zetawar/views.cljs
> +       (str "Configure Faction: "
We should still use translate for the title. We should also add translations for the colors (:blue-name, :red-name, etc.) and use them to lookup the color names.

2017-04-25 18:42 UTC, djwhitt commented on src/cljs/zetawar/views.cljs
> +            (when @faction
I think I would turn this entire 'when' into a 'deftrack' named 'faction-color-name' in the 'subs' ns (accept conn + faction as args).

2017-04-29 16:52 UTC, tbeddy commented
I'll get back to this in a few days.

2017-05-05 19:14 UTC, tbeddy commented on src/cljs/zetawar/views.cljs
> +       (str "Configure Faction: "
I don't oppose using translate at all, but could you explain why it should be used? Consistency?

2017-05-05 22:04 UTC, tbeddy commented on src/cljs/zetawar/views.cljs
> +            (when @faction
What's the reasoning behind having both conn and faction as arguments? Isn't only one necessary to get the desired result?
For example, with faction:
```
(deftrack faction-color-name [faction]
  (when @faction
    (-> @faction ...
```

Or with conn:
```
(deftrack faction-color-name [conn]
  (when-let [faction @(faction-to-configure conn)]
    (-> faction ...
```

Every other deftrack in subs uses conn, so the second would probably be more appropriate.

I might just be missing something obvious.

2017-05-06 02:11 UTC, djwhitt commented on src/cljs/zetawar/views.cljs
> +            (when @faction
Nope, not missing anything, you're totally right. I'd go with the first option so that it's useful in contexts other faction configuration.

2017-05-06 02:11 UTC, djwhitt commented on src/cljs/zetawar/views.cljs
> +       (str "Configure Faction: "
I'm not totally consistent yet, but I'd like to use it for all user visible strings. The reason is two fold. First, it gets the strings out of the UI. I think that's generally cleaner (text changes are separated from UI structure changes). Second, it lets us support multiple languages is the future.

2017-05-06 02:12 UTC, djwhitt commented on src/cljs/zetawar/subs.cljs
> +        (#(apply str [% "-name"]))
Can't this just be (str "-name")?

2017-05-06 15:02 UTC, tbeddy commented on src/cljs/zetawar/subs.cljs
> +        (#(apply str [% "-name"]))
Yeah, it can. Fixed.

2017-05-15 00:04 UTC, tbeddy commented
Thoughts on my changes?

2017-05-15 00:59 UTC, djwhitt commented on src/cljs/zetawar/subs.cljs
> +        (#(str % "-name"))
I think you can eliminate the anonymous function altogether can't you? In other words, turn '(#(str % "-name"))" into '(str "-name")'.

2017-05-15 01:00 UTC, djwhitt commented
Sorry, been busy getting up to speed at a new job. The changes look good. I just added one minor comment. I'll merge after that.

2017-05-15 02:14 UTC, tbeddy commented on src/cljs/zetawar/subs.cljs
> +        (#(str % "-name"))
Yeah, I misunderstood ->. Fixed.

2017-05-15 02:14 UTC, tbeddy commented
No problem, good luck with the job.

2017-05-15 02:37 UTC, djwhitt approved these changes

2017-05-15 02:37 UTC, merged